#!/bin/sh

mkdir -p ipkg/home/retrofw/emus/temper
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/emulators
cp temper ipkg/home/retrofw/emus/temper/temper
cp opk/icon.png ipkg/home/retrofw/emus/temper/temper.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: temper
Version: 20190216
Description: PC ENGINE emulator
Section: emus
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/temper
Depends:
Source: https://github.com/gameblabla/temper' > control

print '2.0' > debian-binary

print 'title=temper
description=PC ENGINE emulator
exec=/home/retrofw/emus/temper/temper
clock=600
selectordir=/home/retrofw/roms
selectorfilter=.pce,.zip,.bin,.cue
' > home/retrofw/apps/gmenu2x/sections/emulators/temper

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../temper.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
